export const GET_CLIENTES = 'GET_CLIENTES'
export const HANDLE_MODAL_CLOSE = "HANDLE_MODAL_CLOSE"
export const HANDLE_MODAL_SHOW = "HANDLE_MODAL_SHOW"
export const CHANGE_THEME = "CHANGE_THEME"
export const GET_LOCALIDADES = "GET_LOCALIDADES"
export const HANDLE_ACTIVE_MODAL = "HANDLE_ACTIVE_MODAL"